apiVersion: v1
kind: Pod
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  containers:
  - name: flask-container
    image: flask-app:latest
    ports:
    - containerPort: 5000
    env:
    - name: NAME
      value: "World"
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "512Mi"
        cpu: "1"
    command: ["python", "server.py"]