apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80      # Service port
    targetPort: 5000  # Container port
    nodePort: 30000  # Port on the node
  type: NodePort