apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-container
        image: mehuljain4751/flask_server:latest
        ports:
        - containerPort: 5000
        env:
        - name: NAME
          value: "World"
        - name: DATABASE_URI
          value: "mysql+mysqlconnector://root:root@mysql-svc.default.svc.cluster.local:3306/flask_data"
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "1"
        command: ["python", "server.py"]